#13: Anforderungen
smartinizer/documentation pull request #18
Opened 2021-05-04 11:45 UTC by DavidSchmidt00

2021-05-05 12:33 UTC, r-franzke requested changes

2021-05-05 12:33 UTC, r-franzke commented on content/03-section.tex
> +
Ich meine es war Bad Practice, wenn nach einer Kapitel-Überschrift kein Text kommt.

2021-05-05 12:33 UTC, r-franzke commented on content/03-section.tex
> +Beim ersten Start, soll er in der Lage sein einen eigenen WLAN \ac{AP} zu öffnen, mit dem sich ein Nutzer verbinden kann. Darüber hinaus soll er in diesem Netzwerk eine Website zur Verfügung stellen,
WLAN sollte als Akronym gekennzeichnet werden.

```suggestion
Beim ersten Start, soll er in der Lage sein einen eigenen WLAN \ac{AP} zu öffnen, mit dem sich ein Nutzer verbinden kann. Darüber hinaus soll er in diesem Netzwerk eine Website zur Verfügung stellen, über die man ihn in ein vorhandenes WLAN anmelden kann. Daraufhin soll er sich bei den nächsten Boot-Vorgängen automatisch mit diesem WLAN verbinden. Sollte das Netzwerk nach einer bestimmten Timeout-Zeit nicht gefunden werden, soll das System wieder in den Setup Modus gehen, in dem der eigene \ac{AP} geöffnet wird, damit der Nutzer den \ac{mcu} mit einem anderen Netzwerk verbinden kann.

```

2021-05-05 12:33 UTC, r-franzke commented on content/03-section.tex
> +Nachdem sich der Mikrocontroller erfolgreich mit dem angegebenen Netzwerk verbunden hat, soll das System eine Website zur Verfügung stellen, über die sich der Mikrocontroller konfigurieren lässt. Hie
Hier noch dazu schreiben, dass die Konfigurations-Möglichkeiten durch die Usecase-Firmware selbst bestimmt werden. Also durch Bereitstellung des Config-Schemas.

2021-05-05 12:33 UTC, r-franzke commented on content/03-section.tex
> +Hat man sich für eine Usecase-Firmware entschieden, wird diese \ac{ota} installiert. Im Nachgang stellt das System weiterhin die Konfigurations-Website zur Verfügung, um die Firmware weiter zu konfig
```suggestion
Hat man sich für eine Usecase-Firmware entschieden, wird diese via \ac{ota} installiert. Im Nachgang stellt das System weiterhin die Konfigurations-Website zur Verfügung, um die Firmware weiter zu konfigurieren oder um eine andere Firmware zu installieren.

```

2021-05-05 12:33 UTC, r-franzke commented on content/03-section.tex
> +Zur Entwicklung neuer Usecase-Firmwares soll eine Art Framework gegeben sein, um die Entwicklung neuer Usecases so einfach wie möglich zu gestaltet. Die Base-Firmware soll dafür in ein neues Arduino-
Hier könnte man noch dazu schreiben, dass Smartinizer unterstützende Funktionalitäten wie das Auslesen der Config bereit stellen sollte.

2021-05-05 19:49 UTC, DavidSchmidt00 commented on content/03-section.tex
> +Nachdem sich der Mikrocontroller erfolgreich mit dem angegebenen Netzwerk verbunden hat, soll das System eine Website zur Verfügung stellen, über die sich der Mikrocontroller konfigurieren lässt. Hie
Das erwähn ich im Abschnitt da drunter, passt da besser

2021-05-06 15:20 UTC, r-franzke approved these changes

2021-05-06 18:03 UTC, merged