Some Fixes
smartinizer/documentation pull request #42
Opened 2021-05-27 13:30 UTC by r-franzke

2021-05-27 19:18 UTC, DavidSchmidt00 requested changes

2021-05-27 19:18 UTC, DavidSchmidt00 commented on content/02-section.tex
> +Mit dem \ac{idf} werden ESP32 Applikationen in der Sprache C geschrieben. \parencite{esoressif_idf}
```suggestion
Mit dem \ac{idf} werden ESP32 Applikationen in der Sprache C geschrieben. \parencite{espressif_idf}

```

2021-05-27 19:18 UTC, DavidSchmidt00 commented on content/02-section.tex
> +Die WiFi-Bibliothek gehört zur den Standardbibliotheken des Arduino Frameworks. Dabei werden zum großteil Funktionen der \ac{idf} verwendet, um die WiFi-Funktionalität zur Verfügung zu stellen. \pare
```suggestion
Die WiFi-Bibliothek gehört zur den Standardbibliotheken des Arduino Frameworks. Dabei werden zum Großteil Funktionen der \ac{idf} verwendet, um die WiFi-Funktionalität zur Verfügung zu stellen. \parencite{arduino_esp32_wifi} 

```

2021-05-27 19:18 UTC, DavidSchmidt00 commented on content/02-section.tex
> +Die WiFi-Bibliothek gehört zur den Standardbibliotheken des Arduino Frameworks. Dabei werden zum großteil Funktionen der \ac{idf} verwendet, um die WiFi-Funktionalität zur Verfügung zu stellen. \pare
zu DEM Großteil

2021-05-27 19:18 UTC, DavidSchmidt00 commented on content/03-section.tex
> +    \caption{Die 4 Sichten der Softwarearchitektur \parencite{kruchten_architecutre_views}}
```suggestion
    \caption{Die 4+1 Sichten der Softwarearchitektur \parencite{kruchten_architecutre_views}}

```

2021-05-27 19:18 UTC, DavidSchmidt00 commented on content/03-section.tex
> +    \caption{Die 4 Sichten der Softwarearchitektur \parencite{kruchten_architecutre_views}}
Hey klau nicht eine Sicht! Das heißt so ^^

2021-05-27 19:18 UTC, DavidSchmidt00 commented on content/04-section.tex
> +    \item{key:} Der Schlüssel identifiziert den Konfigurations-Parameter eindeutig. Über diesen wird später auf die abgespeicherten Wert zugegriffen.
```suggestion
    \item{key:} Der Schlüssel identifiziert den Konfigurations-Parameter eindeutig. Über diesen wird später auf die abgespeicherten Werte zugegriffen.

```

2021-05-27 19:18 UTC, DavidSchmidt00 commented on citations.bib
> +@misc{esoressif_idf,
```suggestion
@misc{espressif_idf,

```

2021-05-27 19:47 UTC, r-franzke commented on content/03-section.tex
> +    \caption{Die 4 Sichten der Softwarearchitektur \parencite{kruchten_architecutre_views}}
Ja aber auf dem Bild sind aber nur 4. Die Use-Case Sicht ist da net drauf xD

2021-05-28 06:22 UTC, DavidSchmidt00 commented on content/03-section.tex
> +    \caption{Die 4 Sichten der Softwarearchitektur \parencite{kruchten_architecutre_views}}
Klaro in der Mitte die "Scenarios"

2021-05-28 08:43 UTC, DavidSchmidt00 submitted a review, later dismissed

2021-05-28 08:50 UTC, merged