#32: Fertigstellung Implementierung + fixes
smartinizer/documentation pull request #43
Opened 2021-05-27 18:57 UTC by DavidSchmidt00

2021-05-27 20:08 UTC, r-franzke requested changes

2021-05-27 20:08 UTC, r-franzke commented on content/04-section.tex
> +    \item \enquote{/connect}: Erwartet eine HTTP-POST Anfrage mit entsprechenden Paramentern und leitet daraufhin die Verbindung zu einem lokalen \ac{wlan}-Netwerk ein.
```suggestion
    \item \enquote{/connect}: Erwartet eine HTTP-POST Anfrage mit entsprechenden Parametern und leitet daraufhin die Verbindung zu einem lokalen \ac{wlan}-Netwerk ein.

```

2021-05-27 20:08 UTC, r-franzke commented on content/04-section.tex
> +Bei größeren Websites muss dieses Vorgehen künfitg überdacht werden, da das Arbeiten mit Strings in C++ sehr ressourcenaufwändig ist.
```suggestion
Bei größeren Websites muss dieses Vorgehen künftig überdacht werden, da das Arbeiten mit Strings in C++ sehr ressourcenaufwändig ist.

```

2021-05-27 20:08 UTC, r-franzke commented on content/04-section.tex
> +Den Ablauf einer Installation wird in \autoref{subsec:ablauf_installation} genauer betrachet.
```suggestion
Den Ablauf einer Installation wird in \autoref{subsec:ablauf_installation} genauer betrachtet.

```

2021-05-27 20:08 UTC, r-franzke commented on content/04-section.tex
> +Um die Anforderungen aus \autoref{sec:anforderungen} bezüglich der einfachen Entwicklung neuer Use Case Firmwares zu erfüllen, musste der Code des Smartinizer Core in eine Bibliothek überführt werden
```suggestion
Um die Anforderungen aus \autoref{sec:anforderungen} bezüglich der einfachen Entwicklung neuer Use Case Firmwaren zu erfüllen, musste der Code des Smartinizer Core in eine Bibliothek überführt werden.

```

2021-05-28 06:19 UTC, DavidSchmidt00 commented on content/04-section.tex
> +\begin{lstlisting}[caption={Konstruktor des MqttHandler},label={lst:sta-setup-status},language=C++]
Ich würd ihn ma da lassen, stört ja nicht

2021-05-28 08:44 UTC, merged